//
//  ContentView 2.swift
//  MakePlayfulDesignsWithShapesSwiftUI206
//
//  Created by 114-1iosClassStudent01 on 2025/9/13.
//


//
//  ContentView.swift
//  p
//
//  Created by 114-1iosClassStudent01 on 2025/9/13.
//

import SwiftUI

struct ContentView: View {
    var body: some View {
        ZStack {
            let myColor = Color(red: 1.0, green: 0.6, blue: 0.8)
            Color(red: 0/255, green: 154/255, blue: 1)
            .ignoresSafeArea()
            Circle().frame(width: 900, height: 900).foregroundStyle(Color(red: 26/255, green: 163/255, blue: 1))
                .offset(x: 150, y: -350)
            Circle().frame(width: 600, height: 600).foregroundStyle(Color(red: 77/255, green: 183/255, blue: 1))
            
                .offset(x: 150, y: -350)
            Circle().frame(width: 400, height: 400).foregroundStyle(Color(red: 1, green: 1, blue: 204/255))
                .offset(x: 150, y: -350)

            Circle().frame(width: 300, height: 300).foregroundStyle(Color(red: 1, green: 1, blue: 120/255))
                .offset(x: 150, y: -350)
            
            Rectangle().frame(width: 500, height: 400).foregroundStyle(Color(red: 0, green: 128/255, blue: 64/255)).offset(x: -10, y: 290)
            Rectangle().trim(from: 0.4, to: 0.7).frame(width: 400, height: 500).foregroundStyle(Color(red: 0, green: 102/255, blue: 51/255)).offset(x: 10, y: 240)
            Rectangle().frame(width: 500, height: 50).foregroundStyle(Color(red: 0, green: 102/255, blue: 51/255)).offset(x: -200, y: 450)
            Ellipse().frame(width: 90, height: 40).foregroundStyle(Color(red: 1, green: 77/255, blue: 166/255))
                .offset(x: -120,y:-50)
                .rotationEffect(.degrees(330))
            Circle().trim(from: 0.8, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -30, y: -45)
            Circle().trim(from: 0.8, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -30, y: -40)
            Circle().trim(from: 0.8, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -30, y: -29)
            Circle().trim(from: 0, to: 0.4)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -30, y: -29)
            Circle()
                .frame(width: 100, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 20, y: -29)
            RoundedRectangle(cornerRadius: 10.0)
                .trim(from: 0.4, to: 0.8)
                .foregroundStyle(myColor)
                .frame(width: 100, height: 100)
                .offset(x: 80, y: 70)
                .rotationEffect(.degrees(180))
            
            Circle()
                .frame(width: 100, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -70, y: 30)
            Circle()
                .frame(width: 100, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -70, y: 80)
            Circle()
                .frame(width: 100, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -60, y: 80)
            Circle()
                .frame(width: 100, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -30, y: 85)
            Circle()
                .frame(width: 100, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -25, y: 86)
            Circle()
                .frame(width: 60, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -80, y: 0)
            Circle()
                .frame(width: 60, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -60, y: 0)
            Circle()
                .frame(width: 60, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -93, y: 50)
            Circle()
                .frame(width: 60, height: 100)
                .foregroundStyle(myColor)
                .offset(x: -96, y: 56)
            Circle()
                .frame(width: 60, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 70, y: 56)
            Circle()
                .frame(width: 60, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 70, y: 78)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 79, y: 69)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 70, y: 90)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 60, y: 90)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 50, y: 100)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 40, y: 100)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 30, y: 110)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 50, y: 10)
            Circle()
                .frame(width: 50, height: 100)
                .foregroundStyle(myColor)
                .offset(x: 55, y: 20)
            Circle()
                .trim(from: 0.45, to: 0.75)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -3, y: -40)
            Circle()
                .trim(from: 0.45, to: 0.75)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -50, y: 10)
                .rotationEffect(.degrees(-40))
            Circle()
                .trim(from: 0.45, to: 0.75)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -10, y: -10)
                .rotationEffect(.degrees(-20))
            Circle()
                .trim(from: 0.45, to: 0.75)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -30, y: -40)
                .rotationEffect(.degrees(-130))
            Circle()
                .trim(from: 0.2, to: 0.45)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -30, y: 40)
            Circle()
                .trim(from: 0.2, to: 0.45)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -28.75, y: 50)
            Circle()
                .trim(from: 0.3, to: 0.45)
                .frame(width: 50, height: 50)
                .foregroundStyle(myColor)
                .offset(x: -90, y: 95)
            Circle()
                .trim(from: 0.85, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -3, y: 65)
            Circle()
                .trim(from: 0, to: 0.3)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 11 ,y: 50)
            Circle()
                .trim(from: 0.75, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 11 ,y: 60)
            Circle()
                .trim(from: 0.85, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 1 ,y: 40)
            Circle()
                .trim(from: 0.85, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 1 ,y: 30)
            Circle()
                .trim(from: 0.85, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 1 ,y: 20)
            Circle()
                .trim(from: 0.85, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 1 ,y: 10)
            Circle()
                .trim(from: 0.85, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 1 ,y: 0)
            Circle()
                .trim(from: 0.65, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: -5 ,y: -40)
            Circle()
                .trim(from: 0.85, to: 1)
                .frame(width: 200, height: 200)
                .foregroundStyle(myColor)
                .offset(x: 1 ,y: -10)
            Circle()
                .frame(width: 50, height: 50)
                .foregroundStyle(myColor)
                .offset(x: 85 ,y: 50)
            Ellipse()
                .frame(width: 100, height: 280)
                .foregroundStyle(myColor)
            Circle().frame(width: 10, height: 10).foregroundStyle(.black).offset(x: -60 ,y: -20)
            Circle().frame(width: 10, height: 10).foregroundStyle(.black).offset(x:10 ,y: -20)
            Rectangle().frame(width: 40, height: 2).foregroundStyle(.black).offset(x: -20 ,y: 30).rotationEffect(.degrees(3))
            Rectangle().frame(width: 30, height: 2).foregroundStyle(.black).offset(x: -15 ,y: 32).rotationEffect(.degrees(-1))
            Ellipse().frame(width: 10, height: 30).foregroundStyle(.blue).offset(x: -2 ,y: 44)
            Ellipse().frame(width: 40, height: 90).foregroundStyle(.red).offset(x: 150 ,y: 70).rotationEffect(.degrees(100))
            Ellipse().frame(width: 90, height: 40).foregroundStyle(.red)
                .offset(x: 40,y:150)
                .rotationEffect(.degrees(-10))
            Ellipse().frame(width: 90, height: 40).foregroundStyle(myColor)
                .offset(x: 120,y:-20)
                .rotationEffect(.degrees(30))
           
            Ellipse().frame(width: 25, height: 10).foregroundStyle(Color(red: 1, green: 77/255, blue: 166/255))
                .offset(x: -80,y:10)
            Ellipse().frame(width: 25, height: 10).foregroundStyle(Color(red: 1, green: 77/255, blue: 166/255))
                .offset(x: 30,y:10).rotationEffect(.degrees(5))
        }
        Text("拜託任天堂不要告我")
        .font(.largeTitle)
        .foregroundStyle(.black)
        .padding()
        .glassEffect()
        .offset(y: -250)
    }
}

#Preview {
    ContentView()
}
